config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'questions#index'
  resources :questions do
    resources :answers, only: [:create]
    resources :comentarios, only: [:create]
    resources :votes, only: [:destroy]
  end
  post 'votes/answer/:id' => 'answers#sum', as: 'answers_votes'

  post 'votes/:id' => 'questions#sum', as: 'question_votes'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :integer          not null, primary key
#  description :text
#  question_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  has_many :votes, as: :votable, dependent: :destroy
  has_many :comentarios, as: :comentable, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comentario.rb
# == Schema Information
#
# Table name: comentarios
#
#  id              :integer          not null, primary key
#  descripcion     :text
#  user_id         :integer
#  comentable_type :string
#  comentable_id   :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Comentario < ApplicationRecord
  belongs_to :user
  belongs_to :comentable, polymorphic: true
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :votes, as: :votable, dependent: :destroy
  has_many :comentarios, as: :comentable, dependent: :destroy
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  has_many :questions, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :comentarios, dependent: :destroy
  has_many :answers, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
# == Schema Information
#
# Table name: votes
#
#  id           :integer          not null, primary key
#  user_id      :integer
#  votable_type :string
#  votable_id   :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :votable, polymorphic: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :require_user, only: [:create, :sum]
  def create
    @answer = Answer.new(answer_params)
    @answer.user_id = current_user.id
    @answer.save
    redirect_to question_path(@answer.question_id)
  end
  def sum
      answer=Answer.find(params[:id])
      answer.votes.create(user_id: current_user.id)
      redirect_to question_path(answer.question_id)
  end

  private
  def answer_params
    params.require(:answer).permit(:description, :question_id )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def require_user
    redirect_to '/users/sign_in' unless current_user
  end
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  def create
    @comentario = Comentario.new(comentario_params)
    @comentario.user_id = current_user.id
    @comentario.save
    redirect_to question_path(params[:question_id])
  end
  def comentario_params
    params.require(:comentario).permit(:descripcion, :comentable_id, :comentable_type )
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :require_user, only: [:new, :sum]

  def index
    @questions = Question.all
  end

  def new
    @question= Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id
    @question.save
    redirect_to question_path(@question)
  end

  def show
    @question = Question.find(params[:id])
    @answer = @question.answers.new
    @comentario = @question.comentarios.new
    @comentarios = @question.comentarios
    @answers = @question.answers
    @d_vote = @question.votes.where(user:current_user)

  end

  def sum
      question=Question.find(params[:id])
			question.votes.create(user_id: current_user.id)
			redirect_to question_path
  end


  private
  def question_params
    params.require(:question).permit(:title, :description)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def destroy
  @vote = Vote.find(params[:id])
  @vote.destroy
  redirect_to question_path(params[:question_id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlowOverstrack</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="/">FlowOverstack</a>
          </div>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li ><%= link_to "Log out ", destroy_user_session_path, method: "delete" %></li>
            <li><a href=""><%=current_user.email%></a></li>
            <% else %>
            <li ><a href="/users/sign_in">Log In</a></li>
            <li><a href="/users/sign_up">Sing Up</a></li>
            <% end %>
          </ul>
        </div>
      </nav>
    <%= yield %>
  </body>
</html>

app/views/questions/edit.html.erb
<h1>Questions#edit</h1>
<p>Find me in app/views/questions/edit.html.erb</p>

app/views/questions/index.html.erb
<div class="contindex">
  <div class="row">
    <div class="col-sm-8">
      <h1>Preguntas</h1>
    </div>
    <div class="col-sm-4">
      <a href="/questions/new" class="btn btn-primary bot-nuevo" role="button">Hacer una pregunta</a>
    </div>
  </div>
  <hr>
  <% @questions.each do |q|%>
    <div class="row" id="num-votos">
      <div class="col-sm-1 text-center" >
        <h2><strong><%= q.votes.count %></strong></h2>
        <p> Votos </p>
      </div>
      <div class="col-sm-2 text-center">
        <h2><strong> <%= q.answers.count %> </strong></h2>
        <p> Respuestas </p>
      </div>
      <div class="col-sm-8 index-pre">
        <h2><%= link_to q.title, question_path(q) %> </h2>
        <p><%= q.description %></p>
      </div>
    </div>
    <hr>
  <%end %>
</div>

app/views/questions/new.html.erb
<div class="row">
  <div class= "col-sm-3">
  </div>
  <div class="contnuevo col-sm-6">
    <h1>Publicar pregunta</h1>
    <%= form_for @question do |f| %>  <!-- cada f hace ref a un field del proyecto --->
      <div>
        <div>
         <%= f.text_field :title, placeholder:"Titulo" %>
       </div>
       <div>
         <%= f.text_area :description, placeholder:"Descrpción"%>
       </div>
      </div>
      <%= f.submit "¡Preguntar!", class: "btn btn-primary botonpre"%>
      <% end %>
    </div>
    <div class= "col-sm-3">
    </div>

</div>

app/views/questions/show.html.erb
<div class="inner-content">
  <div id="question_header">
    <h1><%= @question.title %> </h1>
  </div>
  <div class="row">
    <div class="col-md-1" id="vot-pre">
        <% if @question.votes.exists?(user: current_user) %>
          <% @d_vote.each do |d| %>
            <%= link_to question_vote_path(@question.id,d.id), method: :delete do %>
            <h2 class="glyphicon glyphicon-triangle-top d-vote"  ></h2>
            <% end %>
          <% end %>
        <% else %>
          <%= link_to question_votes_path(@question.id), method: 'post' do %>
            <h2 class="glyphicon glyphicon-triangle-top a-vote"></h2>
          <% end %>
        <% end %>
        <h2 class= 'text-center' style="margin-top:-10px; margin-left:10px"><%= @question.votes.count %><h2>
      </div>

     <div class="col-sm-10" id="comentario">
       <div>
         <p><%= @question.description%> </p>
       </div>
           <% @comentarios.each do |com|%>
           <hr>
              <p class="p"> <%=com.descripcion%> </p>
           <%end%>
       <div>
         <%= form_for @comentario, url: question_comentarios_path(@question)  do | f| %>
             <div>
               <%= f.text_area :descripcion, placeholder:"Agregar comentario"%>
               <%= f.hidden_field  :comentable_id %>
               <%= f.hidden_field  :comentable_type %>
             </div>
             <%= f.submit "Comentar", class: "btn btn-primary botocom"%>
         <% end %>
       </div>
     </div>
  </div>

  <div class="row" id="vot-que">
    <h3> <%=@answers.count %> Respuesta(s) </h3>
    <hr>
    <% @answers.each do |ans|%>
    <% if ans.id == nil %>
    <%else %>
      <div class="row">
        <div class="col-md-1" id="vot-pre">
          <% if ans.votes.exists?(user: current_user) %>
            <%ans.votes.each do |v| %>
              <%= link_to question_vote_path(@question.id,v.id), method: :delete do %>
               <h2 class="glyphicon glyphicon-triangle-top d-vote"  ></h2>
              <% end %>
            <% end %>
          <% else %>
            <%= link_to answers_votes_path(ans.id), method: 'post' do %>
                <h2 class="glyphicon glyphicon-triangle-top a-vote"></h2>
            <% end %>
          <% end %>
            <h2 class= 'text-center' style="margin-top:-10px; margin-left:10px"><%= ans.votes.count %><h2>
        </div>
           <div class="col-sm-9" id="comentario">
             <p><%=ans.description%></p>
             <% ans.comentarios.each do |com|%>
             <hr>
                <p class="p"> <%=com.descripcion%> </p>
             <%end%>
             <div>
               <%= form_for @comentario, url: question_comentarios_path(@question)  do | f| %>
                   <div>
                     <%= f.text_area :descripcion, placeholder:"Agregar comentario"%>
                     <%= f.hidden_field  :comentable_id, :value => ans.id %>
                     <%= f.hidden_field  :comentable_type, :value => "Answer" %>
                   </div>
                   <%= f.submit "Comentar", class: "btn btn-primary botocom"%>
               <% end %>
             </div>
           </div>
      </div>
      <hr>
      <%end%>
    <% end %>
  </div>

  <div>
    <%= form_for @answer, url: question_answers_path(@question)  do | f| %>
        <div>
          <h2> Tu Respuesta </h2>
          <%= f.text_area :description%>
          <%= f.hidden_field  :question_id %>
        </div>
        <%= f.submit "Enviar Respuesta", class: "btn btn-primary botores"%>
    <% end %>
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>